#!/bin/bash
#DIH DI DECRYPT
#BUKAN TOOLS HAPUS DATA INI STER
# SELOW MAH,GW KAN BUKAN BLACK HAT
green='\033[0;32m'
brown='\033[0;33m'
blue='\033[0;34m'

echo -n "Masukkan Facebook Target " | lolcat
read target
echo -e $green "LOADING"
sleep 3
clear
echo -e $green "SEDANG MENCARI FACEBOOK" $target
sleep 2

# if beranda in content
echo -e $green "Facebook" $target "Detected"
sleep 2
# elif beranda in not content
# echo -e $green "Facebokk" $target "MISSING !!"

